### ISSUE TITLE
Errors API: ec2:RunInstances Not authorized for images

### ISSUE THREAD

**Issue by laurablockchain** [vu-h-le/pbi-aws#1]
Hi, this template is not working for me and is coming back with multiple errors such as API: ec2:RunInstances Not authorized for images 

(I had carefully followed all instructions on the following: https://aws.amazon.com/blogs/big-data/integrate-power-bi-with-amazon-redshift-for-insights-and-analytics/ )

Do the AMIs need updating or something? 

Any advice would be much appreciated, thank you.

**Comment by laurablockchain** [comment]
Actually no worries. I've now solved the issue by cloning the code, editing and saving with updated AMIs which I found by following the following instructions https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/finding-an-ami.html

**Comment by vu-h-le** [comment]
> Actually no worries. I've now solved the issue by cloning the code, editing and saving with updated AMIs which I found by following the following instructions https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/finding-an-ami.html

AMIs change quite often, so you'll need to update the default values of AmazonLinuxImageID and WindowsServerImageID input parameters with the latest AMI.  Thanks for the great link @laurablockchain

**Comment by laurablockchain** [comment]
Thanks!
